### ISSUE TITLE
question about dataAmount

### ISSUE THREAD

**Issue by primemb** [jja08111/Learning-Flutter#1]
hey thank you for the nice chart can you tell me what should I put in data amount? my data are like this :
`{value: 11730, sample_time: 1606599486}`
"sample_time" is the beginning of sleep and the value is sleep duration as a second.

I make data awake like this : 

```
DateTime samplteTime = DateTime.fromMillisecondsSinceEpoch(
              element["sample_time"] * 1000);
          DateTime endSleep =
              samplteTime.add(Duration(seconds: int.parse(element["value"])));
          this
              .dataWakeUpTime
              .add(endSleep.hour.toDouble() + (endSleep.minute / 100));
```
and for data amount, I do this but it's not correct : 

```
double amount;
int diffMin = endSleep.difference(samplteTime).inMinutes;
if (diffMin < 60) {
            amount = diffMin / 100;
          } else {
            amount = (diffMin / 60).floor() + (diffMin % 60) / 100;
         }
this.dataAmount.add(amount);
```

this is my data at the end but chart not draw correctly : 

```
labels: [Tue, Tue, Tue, Tue, Tue, Wed, Wed, Wed, Wed, Fri, Fri]
amount: [0.04, 0.08, 0.06, 0.08, 0.11, 0.12, 2.39, 0.23, 2.1, 2.08, 3.42]
wakeup: [21.26, 21.37, 21.46, 22.28, 22.51, 0.03, 3.15, 3.41, 6.0, 2.14, 5.58]
```

![image](https://user-images.githubusercontent.com/3611284/101226918-40d5e800-36ab-11eb-8251-921eb0a0abd9.png)

**Comment by jja08111** [comment]
Hi, thank you for using my chart!

**You just divide `minutes` to `60`, not to `100`.**
Example using your code.
```dart 
DateTime samplteTime = DateTime.fromMillisecondsSinceEpoch(
              element["sample_time"] * 1000);
          DateTime endSleep =
              samplteTime.add(Duration(seconds: int.parse(element["value"])));
          this
              .dataWakeUpTime
            //.add(endSleep.hour.toDouble() + (endSleep.minute / 100));  Before
              .add(endSleep.hour.toDouble() + (endSleep.minute / 60));  //After
``` 
```dart
double amount;
int diffMin = endSleep.difference(samplteTime).inMinutes;
/* Before 
if (diffMin < 60) {
            amount = diffMin / 100;
          } else {
            amount = (diffMin / 60).floor() + (diffMin % 60) / 100;
         }
*/
amount = diffMin / 60;  // After
this.dataAmount.add(amount);
```

I hope you solve this problem.

**Comment by primemb** [comment]
thank you so much for the answer I did those changes now my final data are like this :

```
labels: [Tue, Tue, Tue, Tue, Tue, Wed, Wed, Wed, Wed, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Sat, Sat, Sat, Sat, Sat, Sat, Sat, Sat]
amount: [0.07, 0.13, 0.1, 0.13, 0.18, 0.2, 2.65, 0.38, 2.17, 2.13, 3.7, 0.05, 0.08, 0.05, 0.05, 0.03, 0.05, 0.02, 0.02, 0.03, 0.1, 1.38, 1.58, 0.02, 0.28]
wakeup: [21.43, 21.62, 21.77, 22.47, 22.85, 0.05, 3.25, 3.68, 6.0, 2.23, 5.97, 22.68, 22.95, 23.12, 23.22, 23.3, 23.38, 0.05, 0.63, 2.1, 2.32, 3.93, 5.62, 5.7, 6.0]
```
but I get stuck in an infinite loop in chart_painter.dart line 215 in while loop. mean this "if" never run: 
` if (time == bottomTime) break;`
so I change it too : 
`if (time <= bottomTime) break;`
but still chart draw weird
![image](https://user-images.githubusercontent.com/3611284/101243209-d60cc700-3713-11eb-9d0e-40cf4c8b1c1a.png)

**Comment by jja08111** [comment]
@primemb  
What a nice question! 

I have found a bug that gap between bars is getting too wide.
So, I fix that and you can see [here](https://github.com/jja08111/Learning-Flutter/commit/5b9fc3bd3510f4dd5d3e25d6c938d833213a1dde).

Now, your data correctly work.
![화면 캡처 2020-12-06 001815](https://user-images.githubusercontent.com/57604817/101247017-1d1dab00-375a-11eb-9283-dfcfc2744193.png)

**Comment by primemb** [comment]
thank you so much you are a lifesaver 🥇

**Comment by jja08111** [comment]
@primemb 
[That commit](https://github.com/jja08111/Learning-Flutter/commit/5b9fc3bd3510f4dd5d3e25d6c938d833213a1dde) has bug that draw wrong charts if all `wakeUpTime Data` is smaller than `cuttingHour`. 

[So I have fixed this bug.](https://github.com/jja08111/Learning-Flutter/commit/3334ee125fc2aca09b57fab53e502ebbf31af921)

**Comment by primemb** [comment]
@jja08111 oh thank you so much 💯

**Comment by primemb** [comment]
after the last update, I changed cutting hour to 12 with this data : 

I/flutter (14630): [Mon, Wed, Thu, Fri, Fri, Sat, Sun, Mon]
I/flutter (14630): [3.78, 0.0, 6.18, 4.23, 3.78, 5.58, 0.0, 0.0]
I/flutter (14630): [18.05, 0.0, 15.08, 13.35, 17.7, 15.27, 0.0, 0.0]

**Comment by primemb** [comment]
I try this data with all 24 hours as a "cuttingHour" but charts draw weird again data : 

labels: [Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Thu, Thu, Thu, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Fri, Sat, Sat, Sat, Sat, Sat, Mon]
amount:[0.0, 0.07, 0.13, 0.1, 0.13, 0.18, 0.2, 2.65, 0.38, 2.17, 0.0, 2.13, 3.7, 0.05, 0.08, 0.05, 0.05, 0.03, 0.05, 0.02, 0.02, 0.03, 0.1, 1.38, 1.58, 0.02, 0.28, 0.05, 1.23, 0.95, 3.28, 0.13, 0.0]
wakeup: [0.0, 12.93, 13.12, 13.27, 13.97, 14.35, 15.55, 18.75, 19.18, 21.5, 0.0, 17.73, 21.47, 14.18, 14.45, 14.62, 14.72, 14.8, 14.88, 15.55, 16.13, 17.6, 17.82, 19.43, 21.12, 21.2, 21.5, 15.73, 17.02, 18.0, 21.33, 21.5, 0.0]

![image](https://user-images.githubusercontent.com/3611284/101409125-abc53000-38f2-11eb-99e9-ad1eb820457c.png)

**Comment by primemb** [comment]
I find out it's about timezone problem for example if one person from the USA want to see data from a person in Korea you must handle cuttingHour manually  so people from different countries need different "cuttingHour"

**Comment by jja08111** [comment]
I make the function that calculate `topHour(before: cuttingHour)`.

You can see changes [here](https://github.com/jja08111/Learning-Flutter/commit/190dcfe9364f86c86e9ae5ee736c79bd1d146537#diff-03c2f47c744e1355b9ba60c8ac359c8f832b7bd62a634754b6f08bcb60eb72d2) and [here](https://github.com/jja08111/Learning-Flutter/commit/79ba911142c242c6d374f7a221a5ce9651b51fbc#diff-03c2f47c744e1355b9ba60c8ac359c8f832b7bd62a634754b6f08bcb60eb72d2)

###  **Notice** 
I add assert that `dataAmount` **DO NOT** have `0.0` because the graph draw weird when it has `0.0`.

### After changes
Here is a graph that draw using your data that has deleted `0.0` values.

![화면 캡처 2020-12-08 171727](https://user-images.githubusercontent.com/57604817/101458735-998ed480-397a-11eb-8d97-40d9a5a359ef.png)

**Comment by primemb** [comment]
thank you so much, I add those 0.0 to make all days visible for example if I have data on Tue but don't have any data on Wed and again have data on Thu I want also show that Wed so maybe must add something like this :
label:["Tue","Wed","Thu"]
amount:[1,null,2]
wakeup:[6,null,3]

**Comment by jja08111** [comment]
I didn't know you were using it that way :)

Now, the chart correctly work when you insert `0.0` value at `dataAmountList` to show empty day.

Here is [commit](https://github.com/jja08111/Learning-Flutter/commit/11ecbc7499848bca14ac1dc81e413cf796cc61db).

**Comment by primemb** [comment]
thank you again you save my day I think this chart very stable right now and you can publish it into pub . 🥇
